// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';

export function Attack(arg1:string):Promise<protocol.AttackReply>;

export function Chat(arg1:string,arg2:string):Promise<void>;

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Connected():Promise<boolean>;

export function Disconnect():Promise<void>;

export function Drop(arg1:string):Promise<string>;

export function GroupCreate():Promise<string>;

export function GroupInvite(arg1:string):Promise<void>;

export function GroupJoin(arg1:string):Promise<string>;

export function GroupLeave():Promise<void>;

export function Inventory():Promise<Array<string>>;

export function Look():Promise<protocol.LookReply>;

export function Move(arg1:string):Promise<string>;

export function Quest(arg1:string):Promise<protocol.QuestReply>;

export function Quests():Promise<protocol.QuestsReply>;

export function Send(arg1:string):Promise<string>;

export function Status():Promise<protocol.StatusReply>;

export function Take(arg1:string):Promise<string>;

export function Talk(arg1:string):Promise<string>;

export function Who():Promise<number>;
